/*
 * evon_gpio.c
 *
 *  Created on: 2020. 12. 11.
 *      Author: hyeok
 */

#include "evon_gpio.h"
#include "adc.h"
#include "evon_slv_mbus.h"

#define DOOR_01_ON	 		HAL_GPIO_WritePin(GPIOF, GPIO_PIN_13, GPIO_PIN_SET)
#define DOOR_01_OFF 		HAL_GPIO_WritePin(GPIOF, GPIO_PIN_13, GPIO_PIN_RESET)
#define DOOR_02_ON			HAL_GPIO_WritePin(GPIOF, GPIO_PIN_14, GPIO_PIN_SET)
#define DOOR_02_OFF			HAL_GPIO_WritePin(GPIOF, GPIO_PIN_14, GPIO_PIN_RESET)
#define FAN_01_ON			HAL_GPIO_WritePin(GPIOC, GPIO_PIN_11, GPIO_PIN_SET)
#define FAN_01_OFF			HAL_GPIO_WritePin(GPIOC, GPIO_PIN_11, GPIO_PIN_RESET)
#define FAN_02_ON			HAL_GPIO_WritePin(GPIOC, GPIO_PIN_10, GPIO_PIN_SET)
#define FAN_02_OFF			HAL_GPIO_WritePin(GPIOC, GPIO_PIN_10, GPIO_PIN_RESET)
#define MC_01_ON			HAL_GPIO_WritePin(GPIOB, GPIO_PIN_14, GPIO_PIN_SET)
#define MC_01_OFF			HAL_GPIO_WritePin(GPIOB, GPIO_PIN_14, GPIO_PIN_RESET)
#define MC_02_ON			HAL_GPIO_WritePin(GPIOB, GPIO_PIN_15, GPIO_PIN_SET)
#define MC_02_OFF			HAL_GPIO_WritePin(GPIOB, GPIO_PIN_15, GPIO_PIN_RESET)
#define RELAY_01_02_ON		HAL_GPIO_WritePin(GPIOE, GPIO_PIN_11, GPIO_PIN_SET)
#define RELAY_01_02_OFF		HAL_GPIO_WritePin(GPIOE, GPIO_PIN_11, GPIO_PIN_RESET)
#define RELAY_03_04_ON		HAL_GPIO_WritePin(GPIOE, GPIO_PIN_12, GPIO_PIN_SET)
#define RELAY_03_04_OFF		HAL_GPIO_WritePin(GPIOE, GPIO_PIN_12, GPIO_PIN_RESET)
#define RELAY_05_06_ON		HAL_GPIO_WritePin(GPIOE, GPIO_PIN_13, GPIO_PIN_SET)
#define RELAY_05_06_OFF		HAL_GPIO_WritePin(GPIOE, GPIO_PIN_13, GPIO_PIN_RESET)

#define R_LED_01_ON			HAL_GPIO_WritePin(GPIOB, GPIO_PIN_2, GPIO_PIN_SET)
#define R_LED_01_OFF		HAL_GPIO_WritePin(GPIOB, GPIO_PIN_2, GPIO_PIN_RESET)
#define G_LED_01_ON			HAL_GPIO_WritePin(GPIOF, GPIO_PIN_11, GPIO_PIN_SET)
#define G_LED_01_OFF		HAL_GPIO_WritePin(GPIOF, GPIO_PIN_11, GPIO_PIN_RESET)
#define B_LED_01_ON			HAL_GPIO_WritePin(GPIOF, GPIO_PIN_12, GPIO_PIN_SET)
#define B_LED_01_OFF		HAL_GPIO_WritePin(GPIOF, GPIO_PIN_12, GPIO_PIN_RESET)

#define R_LED_02_ON			HAL_GPIO_WritePin(GPIOE, GPIO_PIN_8, GPIO_PIN_SET)
#define R_LED_02_OFF		HAL_GPIO_WritePin(GPIOE, GPIO_PIN_8, GPIO_PIN_RESET)
#define G_LED_02_ON			HAL_GPIO_WritePin(GPIOE, GPIO_PIN_9, GPIO_PIN_SET)
#define G_LED_02_OFF		HAL_GPIO_WritePin(GPIOE, GPIO_PIN_9, GPIO_PIN_RESET)
#define B_LED_02_ON			HAL_GPIO_WritePin(GPIOE, GPIO_PIN_10, GPIO_PIN_SET)
#define B_LED_02_OFF		HAL_GPIO_WritePin(GPIOE, GPIO_PIN_10, GPIO_PIN_RESET)

#define STATUS_LED_01_ON	HAL_GPIO_WritePin(GPIOG, GPIO_PIN_8, GPIO_PIN_RESET)
#define STATUS_LED_01_OFF	HAL_GPIO_WritePin(GPIOG, GPIO_PIN_8, GPIO_PIN_SET)
#define STATUS_LED_02_ON	HAL_GPIO_WritePin(GPIOG, GPIO_PIN_7, GPIO_PIN_RESET)
#define STATUS_LED_02_OFF	HAL_GPIO_WritePin(GPIOG, GPIO_PIN_7, GPIO_PIN_SET)
#define STATUS_LED_03_ON	HAL_GPIO_WritePin(GPIOG, GPIO_PIN_6, GPIO_PIN_RESET)
#define STATUS_LED_03_OFF	HAL_GPIO_WritePin(GPIOG, GPIO_PIN_6, GPIO_PIN_SET)
#define STATUS_LED_04_ON	HAL_GPIO_WritePin(GPIOG, GPIO_PIN_5, GPIO_PIN_RESET)
#define STATUS_LED_04_OFF	HAL_GPIO_WritePin(GPIOG, GPIO_PIN_5, GPIO_PIN_SET)
#define FAULT_LED_ON		HAL_GPIO_WritePin(GPIOG, GPIO_PIN_4, GPIO_PIN_RESET)
#define FAULT_LED_OFF		HAL_GPIO_WritePin(GPIOG, GPIO_PIN_4, GPIO_PIN_SET)

#define DOOR_01_IN			HAL_GPIO_ReadPin(GPIOF, GPIO_PIN_3)
#define DOOR_02_IN			HAL_GPIO_ReadPin(GPIOF, GPIO_PIN_4)
#define DSEN_01_IN			HAL_GPIO_ReadPin(GPIOF, GPIO_PIN_1)
#define DSEN_02_IN			HAL_GPIO_ReadPin(GPIOF, GPIO_PIN_2)
#define MC_01_IN			HAL_GPIO_ReadPin(GPIOC, GPIO_PIN_15)
#define MC_02_IN			HAL_GPIO_ReadPin(GPIOF, GPIO_PIN_0)
#define RELAY_01_IN			HAL_GPIO_ReadPin(GPIOE, GPIO_PIN_2)
#define RELAY_02_IN			HAL_GPIO_ReadPin(GPIOE, GPIO_PIN_3)
#define RELAY_03_IN			HAL_GPIO_ReadPin(GPIOE, GPIO_PIN_4)
#define RELAY_04_IN			HAL_GPIO_ReadPin(GPIOE, GPIO_PIN_5)
#define RELAY_05_IN			HAL_GPIO_ReadPin(GPIOE, GPIO_PIN_6)
#define RELAY_06_IN			HAL_GPIO_ReadPin(GPIOC, GPIO_PIN_13)

#define EMERGENCY_IN		HAL_GPIO_ReadPin(GPIOB, GPIO_PIN_8)

uGPO g_evon_gpio_out;
uGPI g_evon_gpio_in;

//포인터로 Parameter 받기
uint8_t gpio_out()
{
	//Config 상에서 변경만으로 알 수 있도록 해야함
	(coil(EVON_COIL_MBUS_MAP_DOOR_01_W)) ? DOOR_01_ON : DOOR_01_OFF;
	(coil(EVON_COIL_MBUS_MAP_DOOR_02_W)) ? DOOR_02_ON : DOOR_02_OFF;

	(coil(EVON_COIL_MBUS_MAP_FAN_01_W)) ? FAN_01_ON : FAN_01_OFF;
	(coil(EVON_COIL_MBUS_MAP_FAN_02_W)) ? FAN_02_ON : FAN_02_OFF;

	(coil(EVON_COIL_MBUS_MAP_MC_01_W)) ? MC_01_ON : MC_01_OFF;
	(coil(EVON_COIL_MBUS_MAP_MC_02_W)) ? MC_02_ON : MC_02_OFF;

	(coil(EVON_COIL_MBUS_MAP_RELAY_01_02_W)) ? RELAY_01_02_ON : RELAY_01_02_OFF;
	(coil(EVON_COIL_MBUS_MAP_RELAY_03_04_W)) ? RELAY_03_04_ON : RELAY_03_04_OFF;
	(coil(EVON_COIL_MBUS_MAP_RELAY_05_06_W)) ? RELAY_05_06_ON : RELAY_05_06_OFF;

	(coil(EVON_COIL_MBUS_MAP_R_LED_01_W)) ? R_LED_01_ON : R_LED_01_OFF;
	(coil(EVON_COIL_MBUS_MAP_G_LED_01_W)) ? G_LED_01_ON : G_LED_01_OFF;
	(coil(EVON_COIL_MBUS_MAP_B_LED_01_W)) ? B_LED_01_ON : B_LED_01_OFF;

	(coil(EVON_COIL_MBUS_MAP_R_LED_02_W)) ? R_LED_02_ON : R_LED_02_OFF;
	(coil(EVON_COIL_MBUS_MAP_G_LED_02_W)) ? G_LED_02_ON : G_LED_02_OFF;
	(coil(EVON_COIL_MBUS_MAP_B_LED_02_W)) ? B_LED_02_ON : B_LED_02_OFF;

	(coil(EVON_COIL_MBUS_MAP_STATUS_LED_01_W)) ? STATUS_LED_01_ON : STATUS_LED_01_OFF;
	(coil(EVON_COIL_MBUS_MAP_STATUS_LED_02_W)) ? STATUS_LED_02_ON : STATUS_LED_02_OFF;
	(coil(EVON_COIL_MBUS_MAP_STATUS_LED_03_W)) ? STATUS_LED_03_ON : STATUS_LED_03_OFF;
	(coil(EVON_COIL_MBUS_MAP_STATUS_LED_04_W)) ? STATUS_LED_04_ON : STATUS_LED_04_OFF;
	(coil(EVON_COIL_MBUS_MAP_FAULT_LED_W)) ? FAULT_LED_ON : FAULT_LED_OFF;

	return 1;
}


uint8_t gpio_in()
{
	coilSet(EVON_COIL_MBUS_MAP_DOOR_01_R, DOOR_01_IN);
	coilSet(EVON_COIL_MBUS_MAP_DOOR_02_R, DOOR_02_IN);

	coilSet(EVON_COIL_MBUS_MAP_DSEN_01_R, DSEN_01_IN);
	coilSet(EVON_COIL_MBUS_MAP_DSEN_02_R, DSEN_02_IN);

	coilSet(EVON_COIL_MBUS_MAP_MC_01_R, MC_01_IN);
	coilSet(EVON_COIL_MBUS_MAP_MC_02_R, MC_02_IN);

	coilSet(EVON_COIL_MBUS_MAP_RELAY_01_R, RELAY_01_IN);
	coilSet(EVON_COIL_MBUS_MAP_RELAY_02_R, RELAY_02_IN);
	coilSet(EVON_COIL_MBUS_MAP_RELAY_03_R, RELAY_03_IN);
	coilSet(EVON_COIL_MBUS_MAP_RELAY_04_R, RELAY_04_IN);
	coilSet(EVON_COIL_MBUS_MAP_RELAY_05_R, RELAY_05_IN);
	coilSet(EVON_COIL_MBUS_MAP_RELAY_06_R, RELAY_06_IN);

	coilSet(EVON_COIL_MBUS_MAP_EMERGENCY_R, EMERGENCY_IN);

	/*HAL_GPIO_WritePin(GPIOA, GPIO_PIN_12, GPIO_PIN_SET); //UART4 En_tx_mode
	//HAL_UART_Transmit(&huart1,  &g_evon_gpio_in.all, 4, 10);
	HAL_UART_Transmit(&huart1, &adc_val[3], 2, 10);
	HAL_GPIO_WritePin(GPIOA, GPIO_PIN_12, GPIO_PIN_RESET); //UART4 En_rx_mode*/

	return 1;
}

uint8_t adc_loop()
{
	MDregister[EVON_REGISTER_MBUS_MAP_CCS_01_PD_R] = adc_val[0];
	MDregister[EVON_REGISTER_MBUS_MAP_CCS_01_TEMP_R] = adc_val[1];
	MDregister[EVON_REGISTER_MBUS_MAP_CCS_02_PD_R] = adc_val[2];
	MDregister[EVON_REGISTER_MBUS_MAP_CCS_02_TEMP_R] = adc_val[3];
	MDregister[EVON_REGISTER_MBUS_MAP_DCPT_01_R] = adc_val[4];
	MDregister[EVON_REGISTER_MBUS_MAP_DCPT_02_R] = adc_val[5];
	MDregister[EVON_REGISTER_MBUS_MAP_TEST_TEMP_R] = adc_val[6];

	return 1;
}


