/*
 * modbus.h
 *
 *  Created on: Dec 10, 2020
 *  Author: hyeok0724.kim@eveon.co.kr
 */

#ifndef INC_EVON_SLV_MBUS_H_
#define INC_EVON_SLV_MBUS_H_

#include "main.h"

typedef enum _eEvon_coil_mbus_map
{
	EVON_COIL_MBUS_MAP_DOOR_01_W = 1,
	EVON_COIL_MBUS_MAP_DOOR_02_W,
	EVON_COIL_MBUS_MAP_FAN_01_W,
	EVON_COIL_MBUS_MAP_FAN_02_W,
	EVON_COIL_MBUS_MAP_MC_01_W,
	EVON_COIL_MBUS_MAP_MC_02_W,
	EVON_COIL_MBUS_MAP_RELAY_01_02_W,
	EVON_COIL_MBUS_MAP_RELAY_03_04_W,
	EVON_COIL_MBUS_MAP_RELAY_05_06_W,
	EVON_COIL_MBUS_MAP_R_LED_01_W,
	EVON_COIL_MBUS_MAP_G_LED_01_W,
	EVON_COIL_MBUS_MAP_B_LED_01_W,
	EVON_COIL_MBUS_MAP_R_LED_02_W,
	EVON_COIL_MBUS_MAP_G_LED_02_W,
	EVON_COIL_MBUS_MAP_B_LED_02_W,
	EVON_COIL_MBUS_MAP_STATUS_LED_01_W,
	EVON_COIL_MBUS_MAP_STATUS_LED_02_W,
	EVON_COIL_MBUS_MAP_STATUS_LED_03_W,
	EVON_COIL_MBUS_MAP_STATUS_LED_04_W,
	EVON_COIL_MBUS_MAP_FAULT_LED_W,

	EVON_COIL_MBUS_MAP_DOOR_01_R = 21,
	EVON_COIL_MBUS_MAP_DOOR_02_R,
	EVON_COIL_MBUS_MAP_DSEN_01_R,
	EVON_COIL_MBUS_MAP_DSEN_02_R,
	EVON_COIL_MBUS_MAP_MC_01_R,
	EVON_COIL_MBUS_MAP_MC_02_R,
	EVON_COIL_MBUS_MAP_RELAY_01_R,
	EVON_COIL_MBUS_MAP_RELAY_02_R,
	EVON_COIL_MBUS_MAP_RELAY_03_R,
	EVON_COIL_MBUS_MAP_RELAY_04_R,
	EVON_COIL_MBUS_MAP_RELAY_05_R,
	EVON_COIL_MBUS_MAP_RELAY_06_R,
	EVON_COIL_MBUS_MAP_EMERGENCY_R
} EVON_COIL_MBUS_MAP;

typedef enum _eEvon_register_mbus_map
{
	EVON_REGISTER_MBUS_MAP_CCS_01_PD_R = 0,
	EVON_REGISTER_MBUS_MAP_CCS_01_TEMP_R,
	EVON_REGISTER_MBUS_MAP_CCS_02_PD_R,
	EVON_REGISTER_MBUS_MAP_CCS_02_TEMP_R,
	EVON_REGISTER_MBUS_MAP_DCPT_01_R,
	EVON_REGISTER_MBUS_MAP_DCPT_02_R,
	EVON_REGISTER_MBUS_MAP_TEST_TEMP_R
}EVON_REGISTER_MBUS_MAP;

extern uint8_t MDcoil[20];
extern uint16_t MDregister[50];

void push_ringbuffer(uint8_t comdt);
void located_in_timer(void);
void startSimpleModbus(uint8_t modslaveadr, uint16_t *modbusBufferRegister, uint8_t *modbusBufferCoil);

uint8_t coil(uint16_t MDBSadr);
void coilSet(uint16_t MDBSadr, uint8_t MDBSdata);

#endif /* INC_EVON_SLV_MBUS_H_ */
